import type { MapDef } from "./types"

export const MAPS: MapDef[] = [
  {
    id: 1,
    name: "OPEN FIELD",
    description: "Few obstacles. A gentle warm-up against slow recruits.",
    enemyCount: 4,
    enemySpeed: 1.0,
    enemyFireRate: 1500,
    enemyHp: 2,
    enemyAccuracy: 0.45,
    layout: [
      "...................",
      "..E......E......E..",
      "...................",
      "...BB.......BB.....",
      "...BB.......BB.....",
      "...................",
      ".......BBB.........",
      ".......B.B.........",
      ".......BBB.........",
      "...................",
      ".....SS.....SS.....",
      "...................",
      "........P..........",
      "...................",
      "...................",
    ],
  },
  {
    id: 2,
    name: "BRICK MAZE",
    description: "Walls of brick everywhere. Blast your own paths.",
    enemyCount: 5,
    enemySpeed: 1.15,
    enemyFireRate: 1300,
    enemyHp: 2,
    enemyAccuracy: 0.55,
    layout: [
      "..E.....E.....E....",
      "...................",
      ".BBB.BBBBB.BBBBB.BB",
      ".B...B...B.B...B..B",
      ".B.B.B.B.B.B.B.B.BB",
      ".B.B...B...B.B...B.",
      ".BBBBBBBBBBBBBBBBB.",
      "...................",
      ".BBBBBBBBBBBBBBBBB.",
      ".B...B...B...B...B.",
      ".B.B.B.B.B.B.B.B.B.",
      ".B.B.B.B.B.B.B.B.B.",
      ".....B...P...B.....",
      "...................",
      "...................",
    ],
  },
  {
    id: 3,
    name: "RIVER DELTA",
    description: "Deep water blocks the way. Mind your routes.",
    enemyCount: 5,
    enemySpeed: 1.25,
    enemyFireRate: 1150,
    enemyHp: 3,
    enemyAccuracy: 0.6,
    layout: [
      "..E......E......E..",
      "...................",
      "...WWWW.....WWWW...",
      "...WWWW.....WWWW...",
      "...................",
      "..BB...WWWWW...BB..",
      ".......WWWWW.......",
      ".......WWWWW.......",
      "..BB...WWWWW...BB..",
      "...................",
      "...WWWW.....WWWW...",
      "...WWWW.....WWWW...",
      "........P..........",
      "...................",
      "...................",
    ],
  },
  {
    id: 4,
    name: "DARK FOREST",
    description: "Thick trees hide tanks. Ambushes everywhere.",
    enemyCount: 6,
    enemySpeed: 1.35,
    enemyFireRate: 1050,
    enemyHp: 3,
    enemyAccuracy: 0.65,
    layout: [
      "..E......E......E..",
      "..TTT..TTTTT..TTT..",
      "..TTT..TTTTT..TTT..",
      "...................",
      "TTTTTT.....TTTTTT..",
      "TTTTTT.BB..TTTTTT..",
      ".......BB..........",
      "..TTTTT.....TTTTT..",
      "..TTTTT.....TTTTT..",
      "...................",
      "TTTT...TTTTT...TTTT",
      "TTTT...TTTTT...TTTT",
      "........P..........",
      ".....TTTTTTTTT.....",
      "...................",
    ],
  },
  {
    id: 5,
    name: "IRON FORTRESS",
    description: "Brick, steel, water and trees combined. The final stand.",
    enemyCount: 7,
    enemySpeed: 1.5,
    enemyFireRate: 850,
    enemyHp: 4,
    enemyAccuracy: 0.78,
    layout: [
      ".E......E......E.E.",
      "..S.BB.....BB.S....",
      "..S.BB.WWW.BB.S....",
      "....BB.WWW.BB......",
      ".SSSS.......SSSS...",
      ".....TTT.TTT.......",
      "..BB.TTT.TTT.BB....",
      "..BB.........BB....",
      ".....WWW.WWW.......",
      ".SSSS.WW.WW.SSSS...",
      "...T.........T.....",
      "..BBB.SS.SS.BBB....",
      "........P..........",
      "..TT.........TT....",
      "...................",
    ],
  },
]
